### ISSUE TITLE
Node instance in multiple parentNode.children

### ISSUE THREAD

**Issue by florent-andre** [eush77/unist-util-parents#1]
Hi ! 
Me again suggesting something on a possible misunderstanding ! :)

Do unist trees can be fully used with "node instance" referenced in multiple branch of the tree ? 
If so, one specific node can have multiple parents. 
This is the subject of this suggestion.

### Subject of the feature

`.parent` property in wrapped tree should return multiples parents if the same node instance is referenced in multiple `parentNode.children`. 

### Problem

`.parent` is not usable is this kind of tree as it return only the first one find.
### Expected behaviour

return 'parents' as an array.

### show code 

* an illustrating `jest test` here. I can translate it to a `tape` one if there is interest / value added. 
```js
import parents from 'unist-util-parents'

describe('unist-util-parents feature for node with 2 or more parents', () => {
    it('Return all parents of a node instance in multiple parentNode.children', () => {

        const predicateTree = { type : 'predicateTree', children:[]}
        const parent1 = { type: 'predicate', children:[], id:'http://p/1'}
        const parent2 = { type: 'predicate', children:[], id:'http://p/2'}

        const objectOneParent  = { type: 'object', id:'http://o/1', value:'I only have one parent'}
        const objectTwoParents = { type: 'object', id:'http://o/2', value:'I have 2 parents !'}

        //build the tree
        parent1.children.push(objectTwoParents)
        parent2.children.push(objectTwoParents, objectOneParent)
        predicateTree.children.push(parent1, parent2)

        // wrap it
        const treeWithParents = parents(predicateTree)
        
        // w = wrapped
        const [wparent1, wparent2] = treeWithParents.children

        expect(wparent1.children.length).toBe(1)

        // objectTwoParents is under his 2 parents
        expect(wparent1.children[0]).toStrictEqual(objectTwoParents)
        expect(wparent2.children[0]).toStrictEqual(objectTwoParents)

        // get the wrapped object wO2P = object with 2 parents
        const [wO2P] = wparent2.children

        // but the parent relationship only return one parent
        console.log(wO2P.parent)
        expect(Array.isArray(wO2P.parent)).toBe(true)
    })
})
``` 

Thanks and regards.

**Comment by wooorm** [comment]
There are several things possible in JavaScript, that *should* not happen in unist trees.

One example is the one you point out now, but also for example cyclical references:

```js
var child = {type: 'child', children: []}
var parent = {type: 'parent', children: [child]}
child.children.push(parent)
```

I believe the [unist documentation explains this](https://github.com/syntax-tree/unist#where-this-specification-fits):

> unist relates to JSON in that compliant syntax trees can be expressed completely in JSON.

And furthermore:

> Any value in unist must be expressible in JSON […] This means that the syntax tree should be able to be converted to and from JSON and produce the same tree. For example, in JavaScript, a tree can be passed through `JSON.parse(JSON.stringify(tree))` and result in the same tree.

If a child were to exist in multiple places in a tree, and it would be passed through `JSON`, it would instead result in two separate objects, copies of each other.

I hope that this explains that nodes in unist trees must be unique objects, which can occur exactly once?

---

Interested in hearing what your reasoning for this is!

**Comment by florent-andre** [comment]
Wouha ! Thanks a lot for this !  :heartpulse:  :heartpulse:

I read this some times ago, but not catching all the implications...
Thanks for pointing this out !!
Maybe a side note on cyclical objects and objects references in docs can be useful ? (If I'm not the only one to not get that...).

Are you not afraid of perf / memory usage in case of big trees with many repeating objects ? 

I currently work on "graph style" data (RDF / semantic data), with many repeating objects. 
As it's a graph, each node N1 can have multiples nodes that link to this N1 (aka "parents")
My goal is to provide some "views" of this graph materialized by "Unist trees extractions".

Theses trees extractions are then far more usable than the "graph" one (and benefit of all Unist tools). 
Thinking on this going, I started a draft of an "under the hood" process that generate trees from a graph...
I don't still really know where this going, but I will be happy to share more on this with you if interested. 
Thanks a lot

**Comment by wooorm** [comment]
> Maybe a side note on cyclical objects and objects references in docs can be useful ? (If I'm not the only one to not get that...).

Would you be into a PR, to clarify that? We can work on the perfect wording there?

> Are you not afraid of perf / memory usage in case of big trees with many repeating objects ?

unified / unist trees are used in many projects that I know of that work on huge documents. In almost all cases, basic objects (nodes) are fine, parsing can be improved a bit (micromark), but generally, performance bottlenecks are in plugins and how trees are walked / modified!

> I don't still really know where this going, but I will be happy to share more on this with you if interested.

Yes, please do! Sounds interesting!
